import type { Appointment, BlockedTime, Professional, Procedure, Room, WaitingListItem } from "./types";

export const professionals: Professional[] = [
  { id: "1", name: "Dr. Carlos", specialty: "Implantodontia" },
  { id: "2", name: "Dra. Ana", specialty: "Clínica Geral" },
  { id: "3", name: "Dr. João", specialty: "Ortodontia" },
];

export const rooms: Room[] = [
  { id: "1", name: "Sala 01" },
  { id: "2", name: "Sala 02" },
  { id: "3", name: "Sala Cirúrgica" },
];

export const procedures: Procedure[] = [
  { id: "1", name: "Consulta", duration: 60, price: 200 },
  { id: "2", name: "Implante Unitário", duration: 90, price: 4500 },
  { id: "3", name: "Limpeza + Raspagem", duration: 60, price: 350 },
  { id: "4", name: "Clareamento", duration: 90, price: 850 },
  { id: "5", name: "Tratamento de Canal", duration: 90, price: 1200 },
  { id: "6", name: "Avaliação Ortodôntica", duration: 60, price: 150 },
];

export const appointments: Appointment[] = [
  {
    id: "1",
    patientName: "João Silva",
    procedureName: "Consulta",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "1",
    roomName: "Sala 01",
    date: "2026-06-16",
    startTime: "08:00",
    endTime: "09:00",
    status: "confirmed",
    type: "consultation",
    expectedRevenue: 200,
  },
  {
    id: "2",
    patientName: "Maria Souza",
    procedureName: "Limpeza + Raspagem",
    professionalId: "2",
    professionalName: "Dra. Ana",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-16",
    startTime: "10:00",
    endTime: "11:00",
    status: "in_progress",
    type: "procedure",
    expectedRevenue: 350,
  },
  {
    id: "3",
    patientName: "Pedro Lima",
    procedureName: "Clareamento",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "1",
    roomName: "Sala 01",
    date: "2026-06-16",
    startTime: "14:00",
    endTime: "15:30",
    status: "pending",
    type: "procedure",
    expectedRevenue: 850,
  },
  {
    id: "4",
    patientName: "Ana Lima",
    procedureName: "Avaliação Ortodôntica",
    professionalId: "3",
    professionalName: "Dr. João",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-17",
    startTime: "09:00",
    endTime: "10:00",
    status: "confirmed",
    type: "evaluation",
    expectedRevenue: 150,
  },
  {
    id: "5",
    patientName: "Carlos Melo",
    procedureName: "Implante Unitário",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "3",
    roomName: "Sala Cirúrgica",
    date: "2026-06-17",
    startTime: "10:00",
    endTime: "11:30",
    status: "confirmed",
    type: "procedure",
    expectedRevenue: 4500,
  },
  {
    id: "6",
    patientName: "Fernanda Costa",
    procedureName: "Tratamento de Canal",
    professionalId: "2",
    professionalName: "Dra. Ana",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-18",
    startTime: "08:00",
    endTime: "09:30",
    status: "pending",
    type: "procedure",
    expectedRevenue: 1200,
  },
  {
    id: "7",
    patientName: "Roberto Alves",
    procedureName: "Consulta",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "1",
    roomName: "Sala 01",
    date: "2026-06-18",
    startTime: "11:00",
    endTime: "12:00",
    status: "missed",
    type: "consultation",
    expectedRevenue: 200,
  },
  {
    id: "8",
    patientName: "Juliana Ramos",
    procedureName: "Clareamento",
    professionalId: "2",
    professionalName: "Dra. Ana",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-19",
    startTime: "09:00",
    endTime: "10:30",
    status: "confirmed",
    type: "procedure",
    expectedRevenue: 850,
  },
  {
    id: "9",
    patientName: "Marcos Oliveira",
    procedureName: "Avaliação Ortodôntica",
    professionalId: "3",
    professionalName: "Dr. João",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-19",
    startTime: "14:00",
    endTime: "15:00",
    status: "pending",
    type: "evaluation",
    expectedRevenue: 150,
  },
  {
    id: "10",
    patientName: "Beatriz Santos",
    procedureName: "Limpeza + Raspagem",
    professionalId: "2",
    professionalName: "Dra. Ana",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-20",
    startTime: "08:00",
    endTime: "09:00",
    status: "confirmed",
    type: "procedure",
    expectedRevenue: 350,
  },
  {
    id: "11",
    patientName: "Ricardo Ferreira",
    procedureName: "Consulta",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "1",
    roomName: "Sala 01",
    date: "2026-06-20",
    startTime: "10:00",
    endTime: "11:00",
    status: "confirmed",
    type: "consultation",
    expectedRevenue: 200,
  },
  {
    id: "12",
    patientName: "Camila Dias",
    procedureName: "Implante Unitário",
    professionalId: "1",
    professionalName: "Dr. Carlos",
    roomId: "3",
    roomName: "Sala Cirúrgica",
    date: "2026-06-21",
    startTime: "09:00",
    endTime: "10:30",
    status: "confirmed",
    type: "procedure",
    expectedRevenue: 4500,
  },
  {
    id: "13",
    patientName: "Lucas Pereira",
    procedureName: "Tratamento de Canal",
    professionalId: "2",
    professionalName: "Dra. Ana",
    roomId: "2",
    roomName: "Sala 02",
    date: "2026-06-21",
    startTime: "14:00",
    endTime: "15:30",
    status: "pending",
    type: "procedure",
    expectedRevenue: 1200,
  },
];

export const blockedTimes: BlockedTime[] = [
  {
    id: "block-1",
    professionalId: "1",
    roomId: "1",
    date: "2026-06-21",
    startTime: "12:00",
    endTime: "13:00",
    reason: "Almoço",
  },
  {
    id: "block-2",
    professionalId: "2",
    roomId: "2",
    date: "2026-06-21",
    startTime: "12:00",
    endTime: "13:00",
    reason: "Almoço",
  },
];

export const waitingList: WaitingListItem[] = [
  { id: "w1", patientName: "Carolina Dias", procedureName: "Ortodontia", daysWaiting: 2 },
  { id: "w2", patientName: "Paulo Henrique", procedureName: "Implante", daysWaiting: 5 },
  { id: "w3", patientName: "Luísa Mendes", procedureName: "Clareamento", daysWaiting: 1 },
];
