/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes.$patientId'
import { Route as ConfiguracoesNotificacoesRouteImport } from './routes/configuracoes.notificacoes'
import { Route as AtendimentosPipelineRouteImport } from './routes/atendimentos.pipeline'
import { Route as AtendimentosCampanhasRouteImport } from './routes/atendimentos.campanhas'

const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PacientesRoute,
} as any)
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PacientesRoute,
} as any)
const ConfiguracoesNotificacoesRoute =
  ConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => ConfiguracoesRoute,
  } as any)
const AtendimentosPipelineRoute = AtendimentosPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AtendimentosRoute,
} as any)
const AtendimentosCampanhasRoute = AtendimentosCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AtendimentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/inicio': typeof InicioRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
  '/atendimentos/campanhas': typeof AtendimentosCampanhasRoute
  '/atendimentos/pipeline': typeof AtendimentosPipelineRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/inicio': typeof InicioRoute
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
  '/atendimentos/campanhas': typeof AtendimentosCampanhasRoute
  '/atendimentos/pipeline': typeof AtendimentosPipelineRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atendimentos': typeof AtendimentosRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/inicio': typeof InicioRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
  '/atendimentos/campanhas': typeof AtendimentosCampanhasRoute
  '/atendimentos/pipeline': typeof AtendimentosPipelineRoute
  '/configuracoes/notificacoes': typeof ConfiguracoesNotificacoesRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/auth'
    | '/configuracoes'
    | '/inicio'
    | '/pacientes'
    | '/pagamentos'
    | '/planejamento'
    | '/recebimentos'
    | '/atendimentos/campanhas'
    | '/atendimentos/pipeline'
    | '/configuracoes/notificacoes'
    | '/pacientes/$patientId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/auth'
    | '/configuracoes'
    | '/inicio'
    | '/pagamentos'
    | '/planejamento'
    | '/recebimentos'
    | '/atendimentos/campanhas'
    | '/atendimentos/pipeline'
    | '/configuracoes/notificacoes'
    | '/pacientes/$patientId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/atendimentos'
    | '/auth'
    | '/configuracoes'
    | '/inicio'
    | '/pacientes'
    | '/pagamentos'
    | '/planejamento'
    | '/recebimentos'
    | '/atendimentos/campanhas'
    | '/atendimentos/pipeline'
    | '/configuracoes/notificacoes'
    | '/pacientes/$patientId'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AtendimentosRoute: typeof AtendimentosRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  InicioRoute: typeof InicioRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  PagamentosRoute: typeof PagamentosRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RecebimentosRoute: typeof RecebimentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/pacientes/$patientId': {
      id: '/pacientes/$patientId'
      path: '/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/configuracoes/notificacoes': {
      id: '/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof ConfiguracoesNotificacoesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/atendimentos/pipeline': {
      id: '/atendimentos/pipeline'
      path: '/pipeline'
      fullPath: '/atendimentos/pipeline'
      preLoaderRoute: typeof AtendimentosPipelineRouteImport
      parentRoute: typeof AtendimentosRoute
    }
    '/atendimentos/campanhas': {
      id: '/atendimentos/campanhas'
      path: '/campanhas'
      fullPath: '/atendimentos/campanhas'
      preLoaderRoute: typeof AtendimentosCampanhasRouteImport
      parentRoute: typeof AtendimentosRoute
    }
  }
}

interface AtendimentosRouteChildren {
  AtendimentosCampanhasRoute: typeof AtendimentosCampanhasRoute
  AtendimentosPipelineRoute: typeof AtendimentosPipelineRoute
}

const AtendimentosRouteChildren: AtendimentosRouteChildren = {
  AtendimentosCampanhasRoute: AtendimentosCampanhasRoute,
  AtendimentosPipelineRoute: AtendimentosPipelineRoute,
}

const AtendimentosRouteWithChildren = AtendimentosRoute._addFileChildren(
  AtendimentosRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesNotificacoesRoute: typeof ConfiguracoesNotificacoesRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesNotificacoesRoute: ConfiguracoesNotificacoesRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface PacientesRouteChildren {
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesPatientIdRoute: PacientesPatientIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AtendimentosRoute: AtendimentosRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  InicioRoute: InicioRoute,
  PacientesRoute: PacientesRouteWithChildren,
  PagamentosRoute: PagamentosRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RecebimentosRoute: RecebimentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
