/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecebimentosRouteImport } from './routes/recebimentos'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PagamentosRouteImport } from './routes/pagamentos'
import { Route as IndexRouteImport } from './routes/index'

const RecebimentosRoute = RecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentosRoute = PagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagamentos': typeof PagamentosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/recebimentos': typeof RecebimentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagamentos' | '/planejamento' | '/recebimentos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagamentos' | '/planejamento' | '/recebimentos'
  id: '__root__' | '/' | '/pagamentos' | '/planejamento' | '/recebimentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagamentosRoute: typeof PagamentosRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RecebimentosRoute: typeof RecebimentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recebimentos': {
      id: '/recebimentos'
      path: '/recebimentos'
      fullPath: '/recebimentos'
      preLoaderRoute: typeof RecebimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamentos': {
      id: '/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof PagamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagamentosRoute: PagamentosRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RecebimentosRoute: RecebimentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
