-- Importação de procedimentos/tratamentos do sistema antigo
-- (CSV exportado em 2026-07-01).
-- Gerado por scripts/import_legacy_procedures.py em 2026-07-09T22:46:44.250317Z.
-- 278 procedimentos.
WITH target_owner AS (
  SELECT id FROM auth.users WHERE email = 'raelvvieira@gmail.com' LIMIT 1
)
INSERT INTO public.clinic_procedures (owner_id, name, category, price, tuss_code, tuss_name)
SELECT target_owner.id, v.name, v.category, v.price::numeric, v.tuss_code, v.tuss_name
FROM (VALUES
('Alveoloplastia', 'Cirurgia', 140.00, '82000034', 'Alveoloplastia - por segmento'),
('Amputação Radicular com Obturação Retrógrada', 'Cirurgia', 270.00, '82000050', 'Amputação Radicular com Obturação Retrógrada'),
('Exérese ou Excisão de Cálculo Salivar', 'Cirurgia', 225.00, '82000778', 'Exérese ou Excisão de Cálculo Salivar'),
('Amputação Radicular sem Obturação Retrógrada', 'Cirurgia', 235.00, '82000069', 'Amputação Radicular sem Obturação Retrógrada'),
('Exérese ou Excisão de Cistos Odontológicos', 'Cirurgia', 145.00, '82000786', 'Exérese ou Excisão de Cistos Odontológicos'),
('Exérese ou Excisão de Mucocele', 'Cirurgia', 155.00, '82000794', 'Exérese ou Excisão de Mucocele'),
('Apicetomia Unirradiculares com Obturação Retrógrada', 'Cirurgia', 265.00, '82000174', 'Apicetomia Unirradiculares com Obturação Retrógrada'),
('Exérese ou Excisão de Rânula', 'Cirurgia', 600.00, '82000808', 'Exérese ou Excisão de Rânula'),
('Apicetomia Unirradiculares sem Obturação Retrógrada', 'Cirurgia', 230.00, '82000182', 'Apicetomia Unirradiculares sem Obturação Retrógrada'),
('Exodontia com Retalho', 'Cirurgia', 130.00, '82000816', 'Exodontia a Retalho'),
('Apicetomia Birradiculares com Obturação Retrógrada', 'Cirurgia', 310.00, '82000077', 'Apicetomia Birradiculares com Obturação Retrógrada'),
('Exodontia de Permanente por Indicação Ortodôntica/protética', 'Cirurgia', 100.00, '82000832', 'Exodontia de Permanente por Indicação Ortodôntica/protética'),
('Apicetomia Birradiculares sem Obturação Retrógrada', 'Cirurgia', 275.00, '82000085', 'Apicetomia Birradiculares sem Obturação Retrógrada'),
('Exodontia de Raiz Residual', 'Cirurgia', 110.00, '82000859', 'Exodontia de Raiz Residual'),
('Apicetomia Multirradiculares com Obturação Retrógrada', 'Cirurgia', 350.00, '82000158', 'Apicetomia Multirradiculares com Obturação Retrógrada'),
('Exodontia Simples de Decíduo', 'Cirurgia', 60.00, '83000089', 'Exodontia Simples de Decíduo'),
('Exodontia Simples de Permanente', 'Cirurgia', 100.00, '82000875', 'Exodontia Simples de Permanente'),
('Apicetomia Multirradiculares sem Obturação Retrógrada', 'Cirurgia', 315.00, '82000166', 'Apicetomia Multirradiculares sem Obturação Retrógrada'),
('Frenulectomia Lingual (Frenectomia)', 'Cirurgia', 165.00, '82000891', 'Frenulectomia Lingual'),
('Aumento de Vestíbulo (Sulcoplastia)', 'Cirurgia', 155.00, '82000190', 'Aprofundamento/Aumento de Vestíbulo (Sulcoplastia) – por arcada'),
('Frenulectonia Labial (Frenectomia)', 'Cirurgia', 165.00, '82000883', 'Frenulectonia Labial'),
('Biópsia de Boca', 'Cirurgia', 140.00, '82000239', 'Biópsia de Boca'),
('Frenulotomia Labial (Frenotomia)', 'Cirurgia', 165.00, '82000905', 'Frenulotomia Labial'),
('Biópsia de Glândula Salivar', 'Cirurgia', 140.00, '30204011', 'Biópsia de Glândula Salivar'),
('Frenulotomia Lingual (Frenotomia)', 'Cirurgia', 165.00, '82000913', 'Frenulotomia Lingual'),
('Biópsia de Lábio', 'Cirurgia', 140.00, '30201012', 'Biópsia de Lábio'),
('Exodontia com Odonto-Secção', 'Cirurgia', 186.00, '82001073', 'Odonto-Secção'),
('Biópsia de Língua', 'Cirurgia', 140.00, '30203031', 'Biópsia de Língua'),
('Punção Aspirativa', 'Cirurgia', 140.00, '82001103', 'Punção Aspirativa na Região Buco-maxilo-facial - incluído em qualquer dos procedimentos de "Biópsia"'),
('Reconstrução de Sulco Gengivo-labial', 'Cirurgia', 200.00, '30201080', 'Reconstrução de Sulco Gengivo-labial'),
('Biópsia de Mandíbula', 'Cirurgia', 140.00, '30211018', 'Biópsia de Mandíbula'),
('Redução Cruenta de Fratura Alvéolo Dentária', 'Cirurgia', 170.00, '82001170', 'Redução Cruenta de Fratura Alvéolo Dentária'),
('Biópsia de Maxila', 'Cirurgia', 140.00, '82000280', 'Biópsia de Maxila'),
('Redução Incruenta de Fratura Alvéolo Dentária', 'Cirurgia', 95.00, '82001189', 'Redução Incruenta de Fratura Alvéolo-Dentária'),
('Bridectomia', 'Cirurgia', 165.00, '82000298', 'Bridectomia - por arcada'),
('Exodontia de Dentes Inclusos / Impactados', 'Cirurgia', 245.00, '82001286', 'Remoção de Dentes Inclusos / Impactados'),
('Bridotomia', 'Cirurgia', 165.00, '82000301', 'Bridotomia - por arcada'),
('Exodontia de Dentes Semi-inclusos / impactados', 'Cirurgia', 180.00, '82001294', 'Remoção de Dentes Semi-inclusos / impactados'),
('Remoção de tumores intra ósseos', 'Cirurgia', 250.00, '82001367', 'Remoção de Odontoma - Tumores Intra Ósseos'),
('Cirurgia com Retalho', 'Cirurgia', 130.00, '82000336', 'Cirurgia Odontológica a Retalho'),
('Sepultamento Radicular', 'Cirurgia', 195.00, '82001464', 'Sepultamento Radicular'),
('Cirurgia para Torus Mandibular Bilateral', 'Cirurgia', 220.00, '82000360', 'Cirurgia para Torus Mandibular – Bilateral'),
('Tracionamento Cirúrgico com Finalidade Ortodôntica', 'Cirurgia', 250.00, '82001502', 'Tracionamento Cirúrgico com Finalidade Ortodôntica'),
('Cirurgia para Torus Mandibular Unilateral', 'Cirurgia', 145.00, '82000387', 'Cirurgia para Torus Mandibular - Unilateral'),
('Tratamento Cirúrgico das Fístulas Buco-nasal', 'Cirurgia', 245.00, '82001510', 'Tratamento Cirúrgico das Fístulas Buco-nasal'),
('Cirurgia para Torus Palatinio', 'Cirurgia', 180.00, '82000395', 'Cirurgia para Torus Palatinio'),
('Tratamento Cirúrgico das Fístulas Buco-sinusal', 'Cirurgia', 245.00, '82001529', 'Tratamento Cirúrgico das Fístulas Buco-sinusal'),
('Coleta por Raspagem em Lesões', 'Cirurgia', 120.00, '82000441', 'Coleta de Raspado em Lesões ou Sítios Específicos da Região Buco-maxilo-facial - incluído em qualquer dos procedimentos de "Biópsia"'),
('Tratamento Cirúrgico de Bridas Constritivas', 'Cirurgia', 165.00, '82001545', 'Tratamento Cirúrgico de Bridas Constritivas da Região Buco-maxilo-facial'),
('Tratamento Cirúrgico de Hiperplasias de Tecidos Moles', 'Cirurgia', 180.00, '82001553', 'Tratamento Cirúrgico de Hiperplasias de Tecidos Moles na Região Buco-maxilo-facial'),
('Controle Pós-operatório em Odontologia', 'Cirurgia', 40.00, '82000506', 'Controle Pós-operatório em Odontologia'),
('Tratamento Cirúrgico de Hiperplasias de Tecidos Ósseos', 'Cirurgia', 250.00, '82001588', 'Tratamento Cirúrgico de Hiperplasias de Tecidos Ósseos / Cartilaginosos na Região Buco-maxilo-facial'),
('Enxerto Conjuntivo Subepitelial', 'Cirurgia', 230.00, '82000646', 'Enxerto Conjuntivo Subepitelial - por elemento'),
('Tratamento Cirúrgico dos Tumores Benignos de Tecidos Moles', 'Cirurgia', 180.00, '82001618', 'Tratamento Cirúrgico dos Tumores Benignos de Tecidos Moles na Região Buco-maxilo-facial'),
('Restauração Atraumática em Dente Decíduo', 'Dentística', 50.00, '83000135', 'Restauração Atraumática em Dente Decíduo'),
('Tratamento Cirúrgico de Tumores Benignos de Tecidos Ósseos', 'Cirurgia', 250.00, '82001596', 'Tratamento Cirúrgico de Tumores Benignos de Tecidos Ósseos / Cartilaginosos na Região Buco-maxilo-facial'),
('Tratamento Cirúrgico para Tumores Odontogênicos Benignos', 'Cirurgia', 250.00, '82001634', 'Tratamento Cirúrgico para Tumores Odontogênicos Benignos - sem reconstrução'),
('Restauração Atraumática em Dente Permanente', 'Dentística', 50.00, '85100080', 'Restauração Atraumática em Dente Permanente'),
('Tratamento Conservador de Luxação de ATM', 'Cirurgia', 200.00, '82001642', 'Tratamento Conservador de Luxação da Articulação Têmporo-mandibular - ATM'),
('Ulectomia', 'Cirurgia', 105.00, '82001707', 'Ulectomia'),
('Ulotomia', 'Cirurgia', 100.00, '82001715', 'Ulotomia'),
('Faceta em Resina Fotopolimerizável', 'Dentística', 140.00, '85100064', 'Faceta Direta em Resina Fotopolimerizável'),
('Núcleo de Preenchimento', 'Dentística', 85.00, '85400211', 'Núcleo de Preenchimento'),
('Placa de Clareamento', 'Dentística', 200.00, '85100072', 'Placa de Acetato para Clareamento Caseiro'),
('Fios de PDO liso', 'Harmonização facial', 200.00, NULL, 'Fios de PDO liso'),
('Fios de sustentação (espiculado)', 'Harmonização facial', 350.00, NULL, 'Fios de sustentação (espiculado)'),
('Restauração em Ionômero de Vidro - 1 face', 'Dentística', 60.00, '85100137', 'Restauração em Ionômero de Vidro - 1 face'),
('Lipo de papada cirúrgica', 'Harmonização facial', 1800.00, NULL, 'Lipo de papada cirúrgica'),
('Restauração em Ionômero de Vidro - 2 faces', 'Dentística', 70.00, '85100145', 'Restauração em Ionômero de Vidro - 2 faces'),
('Lipo de papada enzimática', 'Harmonização facial', 350.00, NULL, 'Lipo de papada enzimática'),
('MD codes', 'Harmonização facial', 1000.00, NULL, 'MD codes'),
('Restauração em Ionômero de Vidro - 3 faces', 'Dentística', 75.00, '85100153', 'Restauração em Ionômero de Vidro - 3 faces'),
('Microagulhamento', 'Harmonização facial', 350.00, NULL, 'Microagulhamento'),
('Restauração em Ionômero de Vidro - 4 faces', 'Dentística', 80.00, '85100161', 'Restauração em Ionômero de Vidro - 4 faces'),
('Preenchimento de malar', 'Harmonização facial', 1000.00, NULL, 'Preenchimento de malar'),
('Capeamento Pulpar Direto', 'Endodontia', 90.00, '85100013', 'Capeamento Pulpar Direto'),
('Preenchimento de mandíbula', 'Harmonização facial', 1000.00, NULL, 'Preenchimento de mandíbula'),
('Curativo de Demora', 'Endodontia', 135.00, '85100056', 'Curativo de Demora em Endodontia - incluído nos procedimentos de Tratamentos Endodonticos'),
('Preenchimento de olheiras', 'Harmonização facial', 1000.00, NULL, 'Preenchimento de olheiras'),
('Preparo para Núcleo Intrarradicular', 'Endodontia', 70.00, '85200026', 'Preparo para Núcleo Intrarradicular - incluído no procedimento núcleo metálico fundido- 85400220'),
('Preenchimento de sulco labiomentoniano (marionete)', 'Harmonização facial', 1000.00, NULL, 'Preenchimento de sulco labiomentoniano (marionete)'),
('Preenchimento em fossa canina', 'Harmonização facial', 1000.00, NULL, 'Preenchimento em fossa canina'),
('Pulpotomia', 'Endodontia', 100.00, '85200042', 'Pulpotomia'),
('Preenchimento labial', 'Harmonização facial', 1000.00, NULL, 'Preenchimento labial'),
('Pulpotomia em dente decíduo', 'Endodontia', 100.00, '83000127', 'Pulpotomia em dente decíduo'),
('Preenchimento nas têmporas', 'Harmonização facial', 1000.00, NULL, 'Preenchimento nas têmporas'),
('Pulpectomia', 'Endodontia', 80.00, '85200034', 'Pulpectomia'),
('Skinbooster', 'Harmonização facial', 400.00, NULL, 'Skinbooster'),
('Remoção de Corpo Estranho Intra-Canal', 'Endodontia', 120.00, '85200050', 'Remoção de Corpo Estranho Intra-Canal'),
('Subcision', 'Harmonização facial', 400.00, NULL, 'Subcision'),
('Remoção de Material Obturador', 'Endodontia', 40.00, '85200069', 'Remoção de Material Obturador Intracanal para Retratamento Endodôntico - incluído nos procedimentos de retratamento'),
('Toxina botulínica (botox)', 'Harmonização facial', 1000.00, NULL, 'Toxina botulínica (botox)'),
('Cirurgia Odontológica com Aplicação de Aloenxertos', 'Implantodontia', 2000.00, '82000344', 'Cirurgia Odontológica com Aplicação de Aloenxertos'),
('Remoção de Núcleo Intra-Radicular', 'Endodontia', 150.00, '85200077', 'Remoção de Núcleo Intra-Radicular'),
('Coroa Provisória sobre Implante', 'Implantodontia', 100.00, '85500011', 'Coroa Provisória sobre Implante'),
('Remoção de Trabalho Protético', 'Endodontia', 150.00, '85400505', 'Remoção deTrabalho Protético'),
('Coroa Total Metalo Cerâmica sobre Implante', 'Implantodontia', 600.00, '85500038', 'Coroa Total Metalo Cerâmica sobre Implante'),
('Retratamento Endodôntico Unirradicular', 'Endodontia', 270.00, '85200115', 'Retratamento Endodôntico Unirradicular'),
('Coroa Total Metalo Plástica sobre Implante', 'Implantodontia', 400.00, '85500054', 'Coroa Total Metalo Plástica sobre Implante - Resina Acrílica'),
('Retratamento Endodôntico Birradicular', 'Endodontia', 370.00, '85200093', 'Retratamento Endodôntico Birradicular'),
('Coroa Total Livre de Metal (metal free) sobre Iimplante', 'Implantodontia', 700.00, '85400122', 'Coroa Total Livre de Metal (metalfree) sobre Iimplante - Cerâmica'),
('Retratamento Endodôntico Multirradicular', 'Endodontia', 620.00, '85200107', 'Retratamento Endodôntico Multirradicular'),
('Guia Cirúrgico para Implante', 'Implantodontia', 650.00, '85500062', 'Guia Cirúrgico para Implante - por arcada'),
('Tratamento de Perfuração Endodôntica', 'Endodontia', 170.00, '85200123', 'Tratamento de Perfuração Endodôntica'),
('Implante Ortodôntico', 'Implantodontia', 600.00, '82000964', 'Implante Ortodôntico - por unidade + peça'),
('Tratamento Endodôntico de Dente com Rizogênese Incompleta', 'Endodontia', 100.00, '85200131', 'Tratamento Endodôntico de Dente com Rizogênese Incompleta'),
('Instalação de Implante Ósseo Integrado', 'Implantodontia', 900.00, '82000980', 'Implante Ósseo Integrado - por unidade + peça'),
('Instalação de implante cone morse', 'Implantodontia', 900.00, NULL, 'Instalação de implante cone morse'),
('Tratamento Endodôntico em Dente Decíduo', 'Endodontia', 185.00, '83000151', 'Tratamento Endodôntico em Dente Decíduo'),
('Instalação de implante hexágono externo', 'Implantodontia', 850.00, NULL, 'Instalação de implante hexágono externo'),
('Tratamento Endodôntico Unirradicular', 'Endodontia', 250.00, '85200166', 'Tratamento Endodôntico Unirradicular'),
('Instalação de implante hexágono interno', 'Implantodontia', 850.00, NULL, 'Instalação de implante hexágono interno'),
('Tratamento Endodôntico Birradicular', 'Endodontia', 300.00, '85200140', 'Tratamento Endodôntico Birradicular'),
('Instalação de cicatrizador', 'Implantodontia', 50.00, '82001138', 'Instalação de cicatrizador'),
('Tratamento Endodôntico Multirradicular', 'Endodontia', 475.00, '85200158', 'Tratamento Endodôntico Multirradicular'),
('Protocolo inferior', 'Implantodontia', 14000.00, NULL, 'Protocolo inferior'),
('Bichectomia', 'Harmonização facial', 2500.00, NULL, 'Bichectomia'),
('Protocolo superior', 'Implantodontia', 20000.00, NULL, 'Protocolo superior'),
('Levantamento de seio', 'Implantodontia', 1500.00, NULL, 'Levantamento de seio'),
('Bioestimulador de colágeno', 'Harmonização facial', 1500.00, NULL, 'Bioestimulador de colágeno'),
('Levantamento de seio atraumático', 'Implantodontia', 600.00, NULL, 'Levantamento de seio atraumático'),
('Restauração em Resina Fotopolimerizável 1 face', 'Dentística', 200.00, '85100196', 'Restauração em Resina Fotopolimerizável 1 face'),
('Prótese parcial removível implanto suportada', 'Implantodontia', 1500.00, NULL, 'Prótese parcial removível implanto suportada'),
('Arco Lingual', 'Ortodontia', 285.00, '86000144', 'Arco Lingual'),
('Prótese total removível implanto suportada', 'Implantodontia', 1500.00, NULL, 'Prótese total removível implanto suportada'),
('Instalação de conexão de prótese parafusada', 'Implantodontia', 80.00, NULL, 'Instalação de conexão de prótese parafusada'),
('Instalação de conexão de prótese cimentada', 'Implantodontia', 80.00, NULL, 'Instalação de conexão de prótese cimentada'),
('Aparelho Extra Bucal', 'Ortodontia', 325.00, '86000055', 'Aparelho Extra Bucal'),
('Bionator de Balters', 'Ortodontia', 360.00, '86000179', 'Bionator de Balters'),
('Aparelho Ortodôntico Fixo Metálico', 'Ortodontia', 100.00, '86000098', 'Aparelho Ortodôntico Fixo Metálico - por aparelho'),
('Aparelho Ortodôntico Fixo metálico Parcial', 'Ortodontia', 100.00, '86000110', 'Aparelho Ortodôntico Fixo metálico Parcial - por aparelho'),
('Contenção Fixa', 'Ortodontia', 150.00, '86000209', 'Contenção Fixa - por Arcada'),
('Preenchimento do sulco nasogeniano (bigode chinês)', 'Harmonização facial', 1000.00, NULL, 'Preenchimento do sulco nasogeniano (bigode chinês)'),
('Disjuntor Palatino (Hirax)', 'Ortodontia', 340.00, '86000225', 'Disjuntor Palatino - Hirax'),
('Mascara Facial Delaire e Tração Reversa', 'Ortodontia', 275.00, '86000381', 'Mascara Facial - Delaire e Tração Reversa'),
('Disjuntor Palatino (Macnamara)', 'Ortodontia', 290.00, '86000233', 'Disjuntor Palatino - Macnamara'),
('Mentoneira', 'Ortodontia', 150.00, '86000390', 'Mentoneira'),
('Grade Palatina Fixa', 'Ortodontia', 295.00, '86000314', 'Grade Palatina Fixa'),
('Placa de Haley', 'Ortodontia', 175.00, '86000462', 'Placa de Haley'),
('Placa de Haley com torno expansor', 'Ortodontia', 200.00, '86000470', 'Placa de Haley - com torno expansor'),
('Grade Palatina Removível', 'Ortodontia', 195.00, '86000322', 'Grade Palatina Removível'),
('Manutenção de Aparelho Ortodôntico Removível', 'Ortodontia', 90.00, '86000373', 'Manutenção de Aparelho Ortodôntico - Aparelho Removível - controle mensal'),
('Manutenção de Aparelho Ortodôntico Fixo', 'Ortodontia', 120.00, '86000357', 'Manutenção de Aparelho Ortodôntico - Aparelho Fixo - controle mensal'),
('Placa de Mordida Ortodôntica', 'Ortodontia', 230.00, '86000489', 'Placa de Mordida Ortodôntica'),
('Ajuste Oclusal por Acréscimo', 'Periodontia', 80.00, '85400017', 'Ajuste Oclusal por Acréscimo - incluído nos procedimentos de restauração e prótese'),
('Placa Labio-ativa (Lip bumper)', 'Ortodontia', 250.00, '86000535', 'Placa Labio-ativa'),
('Plano Inclinado', 'Ortodontia', 230.00, '86000551', 'Plano Inclinado'),
('Aumento de Coroa Clínica', 'Periodontia', 190.00, '82000212', 'Aumento de Coroa Clínica'),
('Quadri-Hélice', 'Ortodontia', 295.00, '86000560', 'Quadri-Hélice'),
('Ajuste Oclusal por desgaste', 'Periodontia', 80.00, '85400025', 'Ajuste Oclusal por desgaste seletivo - incluído nos procedimentos de restauração e prótese'),
('Cirurgia Periodontal com Retalho', 'Periodontia', 200.00, '82000417', 'Cirurgia Periodontal a Retalho - por segmento'),
('Cunha Proximal', 'Periodontia', 180.00, '82000557', 'Cunha Proximal'),
('Enxerto com Osso Liofilizado', 'Periodontia', 550.00, '82000620', 'Enxerto c/ Osso Liofilizado'),
('Enxerto Gengival Livre', 'Periodontia', 225.00, '82000662', 'Enxerto Gengival Livre - por segmento/ sextante'),
('Enxerto Pediculado', 'Periodontia', 190.00, '82000689', 'Enxerto Pediculado - por segmento / sextante'),
('Gengivectomia', 'Periodontia', 180.00, '82000921', 'Gengivectomia - por segmento'),
('Gengivoplastia', 'Periodontia', 180.00, '82000948', 'Gengivoplastia - por segmento'),
('Placa de mordida miorelaxante', 'Periodontia', 220.00, '85400270', 'Placa Oclusal Resiliente =placa miorelaxante'),
('Raspagem Sub-gengival (RASUB)', 'Periodontia', 100.00, '85300039', 'Raspagem Sub-gengival e Alisamento Radicular (incluído Curetagem de Bolsa Periodontal) - por elemento'),
('Raspagem Supra-gengival (RAP) - Limpeza', 'Periodontia', 90.00, '85300047', 'Raspagem Supra-gengival (incluído Polimento Coronário) - arcada superior + inferior'),
('Remoção dos Fatores de Retenção de Placa Bacteriana', 'Periodontia', 80.00, '85300055', 'Remoção dos Fatores de Retenção do Biofilme Dental (Placa Bacteriana) - incluído nos procedimentos de profilaxia, restaurações e próteses'),
('Tratamento de Fluorose - microabrasão', 'Periodontia', 85.00, '85100234', 'Tratamento de Fluorose - microabrasão'),
('Tratamento de Gengivite Necrosante Aguda (GNA)', 'Periodontia', 300.00, '85300071', 'Tratamento de Gengivite Necrosante Aguda (GNA) (por sessão)'),
('Tratamento de Pericoronarite', 'Periodontia', 100.00, '85300080', 'Tratamento de Pericoronarite'),
('Tunelização', 'Periodontia', 120.00, '82001685', 'Tunelização'),
('Aplicação de Cariostático', 'Prevenção', 40.00, '84000031', 'Aplicação de Cariostático - por arcada'),
('Aplicação de Selante de Fóssulas e Fissuras', 'Prevenção', 45.00, '84000074', 'Aplicação de Selante de Fóssulas e Fissuras - por elemento'),
('Aplicação Tópica de Flúor', 'Prevenção', 50.00, '84000090', 'Aplicação Tópica de Flúor - por arcada'),
('Aplicação Tópica de Verniz Fluoretado', 'Prevenção', 40.00, '84000112', 'Aplicação Tópica de Verniz Fluoretado'),
('Atividade Educativa em Saúde Bucal', 'Prevenção', 55.00, '84000139', 'Atividade Educativa em Saúde Bucal - incluído a consulta'),
('Atividade Educativa para Pais e/ou Cuidadores de pacientes Especiais', 'Prevenção', 55.00, '87000016', 'Atividade Educativa em Odontologia para Pais e/ou Cuidadores de Pacientes com Necessidades Especiais - incluído a consulta'),
('Atividade Educativa para Pais e/ou Cuidadores', 'Prevenção', 55.00, '87000024', 'Atividade Educativa para Pais e/ou Cuidadores - incluído a consulta'),
('Controle de Biofilme (Placa Bacteriana)', 'Prevenção', 40.00, '84000163', 'Controle de Biofilme (Placa Bacteriana)'),
('Dessensibilização Dentária', 'Prevenção', 55.00, '85300012', 'Dessensibilização Dentária - incluído no procedimento aplicação de verniz fluoretado'),
('Mantenedor de espaço fixo', 'Prevenção', 270.00, '83000097', 'Mantenedor de espaço fixo'),
('Mantenedor de espaço removível', 'Prevenção', 270.00, '83000100', 'Mantenedor de espaço removível'),
('Remineralização Dentária', 'Prevenção', 40.00, '84000201', 'Remineralização Dentária'),
('Coroa de Acetato em Dente Decíduo', 'Prótese', 100.00, '83000020', 'Coroa de Acetato em Dente Decíduo'),
('Coroa de Acetato', 'Prótese', 100.00, '87000040', 'Coroa de Acetato em Dente Permanente'),
('Coroa de Aço em Dente Decíduo', 'Prótese', 160.00, '83000046', 'Coroa de Aço em Dente Decíduo'),
('Coroa de Aço', 'Prótese', 160.00, '87000059', 'Coroa de Aço em Dente Permanente'),
('Coroa de Policarbonato em Dente Decíduo', 'Prótese', 100.00, '83000062', 'Coroa de Policarbonato em Dente Decíduo'),
('Coroa de Policarbonato', 'Prótese', 100.00, '87000067', 'Coroa de Policarbonato em Dente Permanente'),
('Coroa Total Metalo-Plástica', 'Prótese', 230.00, '85400173', 'Coroa Total Metalo-Plástica - Resina Acrílica'),
('Coroa Provisória com Pino', 'Prótese', 130.00, '85400076', 'Coroa Provisória com Pino'),
('Coroa Provisória sem Pino', 'Prótese', 110.00, '85400084', 'Coroa Provisória sem Pino'),
('Radiografia Panorâmica com Traçado Cefalométrico', 'Radiologia', 70.00, '81000413', 'Radiografia Panorâmica de Mandíbula/Maxila (ortopantomografia) com Traçado Cefalométrico'),
('Coroa Total Acrílica Prensada', 'Prótese', 230.00, '85400092', 'Coroa Total Acrílica Prensada'),
('Coroa Total em Cerâmica Pura', 'Prótese', 660.00, '85400106', 'Coroa Total em Cerâmica Pura (Metal free)'),
('Coroa Total em Cerômero', 'Prótese', 350.00, '85400114', 'Coroa Total em Cerômero – inclui a peça protética'),
('Coroa Total Metálica', 'Prótese', 330.00, '85400149', 'Coroa Total Metálica - inclui a peça protética'),
('Radiografia Periapical', 'Radiologia', 15.00, '81000421', 'Radiografia Periapical'),
('Coroa Total Metalo Cerâmica', 'Prótese', 585.00, '85400157', 'Coroa Total Metalo Cerâmica'),
('Teleradiografia com Traçado', 'Radiologia', 85.00, '81000480', 'Teleradiografia com Traçado Computadorizado'),
('Faceta em Cerâmica Pura', 'Prótese', 575.00, '85400181', 'Faceta em Cerâmica Pura'),
('Traçado Cefalométrico', 'Radiologia', 30.00, '81000537', 'Traçado Cefalométrico'),
('Faceta em Cerômero', 'Prótese', 300.00, '85400190', 'Faceta em Cerômero'),
('Guia Cirúrgico para Prótese Imediata', 'Prótese', 280.00, '85400203', 'Guia Cirúrgico para Prótese Imediata'),
('Teleradiografia sem Traçado', 'Radiologia', 70.00, NULL, 'Teleradiografia sem Tracado Computadorizado'),
('Núcleo Metálico Fundido', 'Prótese', 200.00, '85400220', 'Núcleo Metálico Fundido - inclui a peça protética'),
('Radiografia da Mão (Carpal)', 'Radiologia', 75.00, NULL, 'Radiografia da Mão (Carpal)'),
('Pino Pré Fabricado', 'Prótese', 130.00, '85400262', 'Pino Pré Fabricado'),
('Tomografia', 'Radiologia', 200.00, NULL, 'Tomografia'),
('Prótese Fixa Adesiva em Cerômero (metal free)', 'Prótese', 500.00, '85400297', 'Prótese Fixa Adesiva em Cerômero Livre de Metal (metal free)'),
('Radiografia de ATM', 'Radiologia', 130.00, '81000340', 'Radiografia de ATM'),
('Prótese Fixa Adesiva Direta (provisória)', 'Prótese', 250.00, '85400289', 'Prótese Fixa Adesiva Direta (provisória)'),
('Radiografia póstero-anterior', 'Radiologia', 70.00, '81000430', 'Radiografia póstero-anterior'),
('Prótese Fixa Adesiva Indireta em Metálo Cerâmica 3 elementos', 'Prótese', 1050.00, '85400300', 'Prótese Fixa Adesiva Indireta em Metálo Cerâmica - 3 elementos'),
('Prótese Fixa Adesiva Indireta em Metalo-Plástica 3 elementos', 'Prótese', 755.00, '85400319', 'Prótese Fixa Adesiva Indireta em Metalo-Plástica - 3 elementos'),
('Diagnóstico Anatomopatológico em Citologia Esfoliativa', 'Testes e exames laboratoriais', 120.00, '81000111', 'Diagnóstico Anatomopatológico em Citologia Esfoliativa na região Buco-maxilo-facial'),
('Prótese Parcial Fixa em Metálo Cerâmica', 'Prótese', 780.00, '85400335', 'Prótese Parcial Fixa em Metálo Cerâmica - por elemento'),
('Diagnóstico Anatomopatológico em Material de Biópsia', 'Testes e exames laboratoriais', 140.00, '81000138', 'Diagnóstico Anatomopatológico em Material de Biópsia na Região Buco-maxilo-facial'),
('Prótese Parcial Fixa em Metálo Plástica', 'Prótese', 600.00, '85400343', 'Prótese Parcial Fixa em Metálo Plástica - por elemento'),
('Diagnóstico Anatomopatológico em Peça Cirurgica', 'Testes e exames laboratoriais', 140.00, '81000154', 'Diagnóstico Anatomopatológico em Peça Cirurgica na Região Buco-maxilo-facial'),
('Prótese Parcial Removível com Grampos Bilateral (PPR)', 'Prótese', 980.00, '85400386', 'Prótese Parcial Removível com Grampos Bilateral'),
('Diagnóstico Anatomopatológico em Punção', 'Testes e exames laboratoriais', 50.00, '81000170', 'Diagnóstico Anatomopatológico em Punção na Região Buco-maxilo-facial'),
('Prótese Parcial Removível com Encaixes (PPR)', 'Prótese', 1320.00, '85400378', 'Prótese Parcial Removível com Encaixes de Precisão ou Semi Precisão'),
('Diagnóstico por Meio de Enceramento', 'Testes e exames laboratoriais', 50.00, '81000243', 'Diagnóstico por Meio de Enceramento (por arcada)'),
('Prótese Parcial Removível Provisória (PPR)', 'Prótese', 560.00, '85400394', 'Prótese Parcial Removível Provisória em Acrílico com ou sem Grampos'),
('Prótese Total (PT)', 'Prótese', 1250.00, '85400408', 'Prótese Total - Superior ou Inferior'),
('Teste de Fluxo Salivar', 'Testes e exames laboratoriais', 50.00, '41401654', 'Teste de Fluxo Salivar'),
('Prótese Total Imediata (PT)', 'Prótese', 800.00, '85400416', 'Prótese Total Imediata - Superior ou Inferior'),
('Teste de PH da Saliva', 'Testes e exames laboratoriais', 50.00, '84000252', 'Teste de PH da Saliva'),
('Prótese Total Incolor (PT)', 'Prótese', 1250.00, '85400424', 'Prótese Total Incolor - Superior ou Inferior.'),
('Consulta Odontológica de Urgência', 'Urgência', 100.00, '81000049', 'Consulta Odontológica de Urgência (tratamento de odontalgia aguda)'),
('Provisório para Faceta', 'Prótese', 70.00, '85400432', 'Provisório para Faceta - incluído no procedimento de "Restauração com Faceta"'),
('Consulta Odontológica de Urgência 24 horas', 'Urgência', 150.00, '81000057', 'Consulta Odontológica de Urgência 24 horas'),
('Provisório para Inlay/Onlay', 'Prótese', 50.00, '85400440', 'Provisório para Inlay/Onlay - incluído nos procedimentos de "Restauração Inlay/Onlay"'),
('Colagem de Fragmentos Dentários', 'Urgência', 150.00, '85100048', 'Colagem de Fragmentos Dentários'),
('Provisório para Restauração Metálica Fundida (RMF)', 'Prótese', 50.00, '85400459', 'Provisório para Restauração Metálica Fundida (RMF) - incluído no procedimento de "RMF"'),
('Controle de Hemorragia com Aplicação de Agente Hemostático', 'Urgência', 100.00, '82000468', 'Controle de Hemorragia com Aplicação de Agente Hemostático em região Buco-maxilo-facial'),
('Reembasamento de Coroa Provisória', 'Prótese', 50.00, '85400475', 'Reembasamento de Coroa Provisória'),
('Reembasamento de Prótese Total ou Parcial em Consultório', 'Prótese', 150.00, '85400483', 'Reembasamento de Prótese Total ou Parcial - Imediato (em Consultório)'),
('Controle de Hemorragia sem Aplicação de Agente Hemostático', 'Urgência', 100.00, '82000484', 'Controle de Hemorragia sem Aplicação de Agente Hemostático em região Buco-maxilo-facial'),
('Reembasamento de Prótese Total ou Parcial em Laboratório', 'Prótese', 290.00, '85400491', 'Reembasamento de Prótese Total ou Parcial - Imediato (em Laboratório)'),
('Sutura de Ferida', 'Urgência', 60.00, '82001499', 'Sutura de Ferida em região Buco-Maxilo-Facial'),
('Restauração Inlay', 'Prótese', 250.00, '85100170', 'Restauração em Resina ( indireta) - Inlay'),
('Restauração Onlay', 'Prótese', 250.00, '85100188', 'Restauração em Resina ( indireta) - Onlay'),
('Tratamento de Alveolite', 'Urgência', 80.00, '82001650', 'Tratamento de Alveolite'),
('Restauração Inlay em Cerâmica Pura', 'Prótese', 570.00, '85400513', 'Restauração em Cerâmica Pura - Inlay'),
('Imobilização Dentária em Dentes Decíduos', 'Urgência', 150.00, '85000787', 'Imobilização Dentária em Dentes Decíduos'),
('Restauração Onlay em Cerâmica Pura', 'Prótese', 570.00, '85400521', 'Restauração em Cerâmica Pura - Onlay'),
('Imobilização Dentária em Dentes Permanentes', 'Urgência', 150.00, '85300020', 'Imobilização Dentária em Dentes Permanentes'),
('Restauração Metálica Fundida', 'Prótese', 285.00, '85400556', 'Restauração Metálica Fundida - inclui a peça protética'),
('Incisão e Drenagem Extra Oral de Abscesso', 'Urgência', 100.00, '82001022', 'Incisão e Drenagem Extra Oral de Abscesso, Hematoma e/ou Flegmão da Região Buco-Maxilo-Facial'),
('Fotografia - Unidade', 'Radiologia', 15.00, '81000278', 'Fotografia - Unidade'),
('Levantamento Radiográfico', 'Radiologia', 150.00, '81000294', 'Levantamento Radiográfico (Exame Radiodôntico) - valor por radiografia - máximo de 14 RX'),
('Modelos Ortodônticos- Par', 'Radiologia', 75.00, '81000308', 'Modelos Ortodônticos- Par'),
('Radiografia Interproximal - Bite-Wing', 'Radiologia', 15.00, '81000375', 'Radiografia Interproximal - Bite-Wing'),
('Incisão e Drenagem Intra Oral de Abscesso', 'Urgência', 80.00, '82001030', 'Incisão e Drenagem Intra Oral de Abscesso, Hematoma e/ou Flegmão da Região Buco-Maxilo-Facial'),
('Radiografia Oclusal', 'Radiologia', 30.00, '40801187', 'Radiografia Oclusal'),
('Radiografia Panorâmica', 'Radiologia', 70.00, '81000405', 'Radiografia Panorâmica de Mandíbula / Maxila (ortopantomografia)'),
('Recimentação de Trabalhos Protéticos', 'Urgência', 45.00, '85400467', 'Recimentação de Trabalhos Protéticos'),
('Consulta de Auditoria - perícia inicial', 'Outros', 60.00, NULL, 'Consulta Odontológica para Avaliação Técnica de Auditoria - perícia inicial'),
('Redução Simples de Luxação de ATM', 'Urgência', 150.00, '82001197', 'Redução Simples de Luxação de Articulação Têmporo-Mandibular (ATM)'),
('MYOBRACE', 'Ortodontia', 1500.00, NULL, 'MYOBRACE'),
('Reimplante Dentário com Contenção', 'Urgência', 150.00, '82001251', 'Reimplante Dentário com Contenção'),
('Clareamento Dentário Caseiro', 'Dentística', 350.00, '85100021', 'Clareamento Dentário Caseiro - por arcada'),
('Tratamento de Abscesso Periodontal agudo', 'Urgência', 80.00, '85300063', 'Tratamento de Abscesso Periodontal agudo'),
('Clareamento em Consultório', 'Dentística', 250.00, '85100030', 'Clareamento Dentário em Consultório - por arcada'),
('Consulta odontológica', 'Outros', 60.00, '81000030', 'Consulta odontológica'),
('Profilaxia + Polimento Coronário - Limpeza', 'Prevenção', 200.00, '84000198', 'Profilaxia + Polimento Coronário - arcada superior + inferior'),
('Consulta de Retorno', 'Outros', 50.00, NULL, 'Consulta de Retorno'),
('Restauração em Resina Fotopolimerizável 2 faces', 'Dentística', 250.00, '85100200', 'Restauração em Resina Fotopolimerizável 2 faces'),
('Consulta Inicial', 'Outros', 80.00, '81000065', 'Consulta Odontológica Inicial'),
('Restauração em Resina Fotopolimerizável 3 faces', 'Dentística', 300.00, '85100218', 'Restauração em Resina Fotopolimerizável 3 faces'),
('Consulta de Auditoria - perícia final', 'Outros', 60.00, '81000073', 'Consulta Odontológica para Avaliação Técnica de Auditoria - perícia final'),
('Restauração em Resina Fotopolimerizável 4 faces', 'Dentística', 350.00, '85100226', 'Restauração em Resina Fotopolimerizável 4 faces / ângulo'),
('Falta a Consulta', 'Outros', 65.00, NULL, 'Falta a Consulta'),
('Prótese Protocolo All On For', 'Cirurgia', 6500.00, NULL, 'Prótese Protocolo All On For'),
('Condicionamento em Odontologia', 'Outros', 50.00, '81000014', 'Condicionamento em Odontologia (máximo 03 sessões por ano)'),
('Aluguel do Consultório (Por Hora)', 'Outros', 90.00, NULL, 'Aluguel do Consultório (Por Hora)'),
('Condicionamento em Odontologia para pacientes especiais', 'Outros', 50.00, '87000032', 'Condicionamento em Odontologia para pacientes com necessidades especiais'),
('Aluguel do Consultório ( 1 Turno)', 'Cirurgia', 200.00, NULL, 'Aluguel do Consultório ( 1 Turno)'),
('Tratamento Ortodôntico com Alinhadores (aligners)', 'Ortodontia', 7000.00, NULL, NULL),
('Preenchimento de mento', 'Harmonização facial', 1000.00, NULL, 'Preenchimento de mento'),
('Contenção de Acetato', 'Ortodontia', 250.00, NULL, 'Contenção de Acetato'),
('Rinomodelação', 'Harmonização facial', 1700.00, NULL, 'Rinomodelação')
) AS v(name, category, price, tuss_code, tuss_name)
CROSS JOIN target_owner;
